# Generated by Django 5.2.17 on 2026-09-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment', models.CharField(max_length=200)),
                ('etage', models.CharField(blank=True, max_length=50)),
                ('salle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'localisation',
                'verbose_name_plural': 'localisations',
                'ordering': ['batiment', 'etage', 'salle'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inventaire', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'inventaire")),
                ('nom', models.CharField(max_length=300)),
                ('type_equipement', models.CharField(max_length=200, verbose_name="Type d'équipement")),
                ('categorie', models.CharField(max_length=200)),
                ('marque', models.CharField(max_length=200)),
                ('modele', models.CharField(max_length=200)),
                ('num_serie', models.CharField(max_length=200, verbose_name='Numéro de série')),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_installation', models.DateField(blank=True, null=True)),
                ('date_mise_service', models.DateField(blank=True, null=True)),
                ('etat_operationnel', models.CharField(choices=[('FONCTIONNEL', 'Fonctionnel'), ('FONCTIONNEL_SOUS_SURVEILLANCE', 'Fonctionnel sous surveillance'), ('EN_PANNE', 'En panne'), ('EN_MAINTENANCE', 'En maintenance'), ('EN_ATTENTE_PIECE_OU_PRESTATAIRE', 'En attente de pièce ou prestataire'), ('HORS_SERVICE', 'Hors service'), ('REFORME', 'Réformé')], default='FONCTIONNEL', max_length=40)),
                ('niveau_criticite', models.CharField(choices=[('CRITIQUE', 'Critique'), ('ELEVE', 'Élevé'), ('MOYEN', 'Moyen'), ('FAIBLE', 'Faible')], default='MOYEN', max_length=20)),
                ('statut_cycle_vie', models.CharField(choices=[('RECEPTION', 'Réception'), ('INSTALLATION', 'Installation'), ('MISE_EN_SERVICE', 'Mise en service'), ('EXPLOITATION', 'Exploitation'), ('MAINTENANCE', 'Maintenance'), ('REFORME', 'Réformé')], default='EXPLOITATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='equipment.localisation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='equipment.service')),
            ],
            options={
                'verbose_name': 'équipement',
                'verbose_name_plural': 'équipements',
                'ordering': ['-created_at'],
            },
        ),
    ]
