# Generated by Django 5.2.17 on 2026-09-18 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("failures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "Corrective"),
                            ("PREVENTIVE", "Preventive"),
                            ("PREDICTIVE", "Predictive"),
                            ("AMELIORATIVE", "Ameliorative"),
                        ],
                        default="CORRECTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PLANIFIEE", "Planifiee"),
                            ("EN_COURS", "En cours"),
                            ("TERMINEE", "Terminee"),
                            ("ANNULEE", "Annulee"),
                        ],
                        default="PLANIFIEE",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(verbose_name="Description de l'intervention")),
                ("pieces_utilisees", models.TextField(blank=True, verbose_name="Pièces utilisées")),
                (
                    "temps_passe_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="Temps passé (minutes)"),
                ),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "panne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="failures.panne",
                    ),
                ),
                (
                    "realisee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interventions_realisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "intervention",
                "verbose_name_plural": "interventions",
                "ordering": ["-created_at"],
            },
        ),
    ]
