# Generated by Django 5.2.17 on 2026-09-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='panne',
            name='affecte_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes_affectees', to=settings.AUTH_USER_MODEL, verbose_name='Affectée à'),
        ),
    ]
