# Generated by Django 5.2.17 on 2026-09-22 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("entite", models.CharField(max_length=100)),
                ("entite_id", models.PositiveIntegerField()),
                ("ancienne_valeur", models.JSONField(blank=True, null=True)),
                ("nouvelle_valeur", models.JSONField(blank=True, null=True)),
                ("horodatage", models.DateTimeField(auto_now_add=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "log d'audit",
                "verbose_name_plural": "logs d'audit",
                "ordering": ["-horodatage"],
            },
        ),
    ]
